server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zyz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  application:
    name: roleservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务端地址
