server:
  port: 8084
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zyz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  application:
    name: logservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  data:
    redis:
      host: localhost
      port: 6379

# PageHelper 配置
pagehelper:
  helperDialect: mysql  # 设置数据库方言为 MySQL
  reasonable: true       # 设置合理化参数
